services:
  db:
    image: postgres:16
    container_name: placas_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: placas_db
    ports:
      - "5432:5432"
    volumes:
      - placas_pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: placas_api
    restart: always
    depends_on:
      - db
    environment:
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: placas_db
    ports:
      - "8000:8000"
    volumes:
      - .:/backend

volumes:
  placas_pgdata:
